name: BossCreator
version: rc-2
main: com.BossCreator.Main
api-version: 1.16
softdepend: [HolographicDisplays, PlaceholderAPI]
commands:
  createboss:
    usage: /createboss <id>
    description: creating and spawn boss in player location
  spawnboss:
    usage: /spawnboss <id>
    description: spawn boss in cfg location
  tpboss:
    usage: /tpboss <id>
    description: teleport to boss
  deleteboss:
    usage: /deleteboss <id>
    description: delete boss